# Generated by Django 3.0.5 on 2020-06-27 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20200627_2002'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Opener',
            new_name='Artist',
        ),
        migrations.RenameField(
            model_name='concert',
            old_name='openers',
            new_name='artists',
        ),
        migrations.RemoveField(
            model_name='concert',
            name='artist',
        ),
    ]
